import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtemp, mkdir, writeFile, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { compileAll } from "../src/compiler.js";
import { DEFAULT_CONFIG, type OpenSpecConfig } from "../src/types.js";

let tempDir: string;

beforeEach(async () => {
  tempDir = await mkdtemp(join(tmpdir(), "openspec-test-"));
  await mkdir(join(tempDir, ".openspec", "modules"), { recursive: true });
});

afterEach(async () => {
  await rm(tempDir, { recursive: true, force: true });
});

describe("compileAll", () => {
  it("generates output files for all enabled targets", async () => {
    await writeFile(
      join(tempDir, ".openspec", "modules", "rules.md"),
      "---\nname: Rules\n---\n# Rules\n\n- Follow conventions"
    );

    const config: OpenSpecConfig = {
      ...DEFAULT_CONFIG,
      targets: {
        claude: { enabled: true, output: "CLAUDE.md" },
        cursor: { enabled: true, output: ".cursorrules" },
      },
    };

    const results = await compileAll(tempDir, config);

    expect(results).toHaveLength(2);
    expect(results.every((r) => !r.skipped && !r.error)).toBe(true);

    const claudeContent = await readFile(join(tempDir, "CLAUDE.md"), "utf-8");
    expect(claudeContent).toContain("Generated by openspec");
    expect(claudeContent).toContain("## Rules");
    expect(claudeContent).toContain("Follow conventions");
    // Should NOT have duplicate heading
    expect(claudeContent).not.toContain("# Rules\n\n## Rules");

    const cursorContent = await readFile(join(tempDir, ".cursorrules"), "utf-8");
    expect(cursorContent).toContain("Generated by openspec");
    expect(cursorContent).toContain("## Rules");
  });

  it("skips disabled targets", async () => {
    await writeFile(
      join(tempDir, ".openspec", "modules", "rules.md"),
      "---\nname: Rules\n---\nSome rules."
    );

    const config: OpenSpecConfig = {
      ...DEFAULT_CONFIG,
      targets: {
        claude: { enabled: true, output: "CLAUDE.md" },
        cursor: { enabled: false, output: ".cursorrules" },
      },
    };

    const results = await compileAll(tempDir, config);
    const claudeResult = results.find((r) => r.target === "claude")!;
    const cursorResult = results.find((r) => r.target === "cursor")!;

    expect(claudeResult.skipped).toBe(false);
    expect(cursorResult.skipped).toBe(true);
  });

  it("returns empty results when no modules exist", async () => {
    const results = await compileAll(tempDir, DEFAULT_CONFIG);
    expect(results).toHaveLength(0);
  });

  it("creates parent directories for output files", async () => {
    await writeFile(
      join(tempDir, ".openspec", "modules", "rules.md"),
      "Some rules."
    );

    const config: OpenSpecConfig = {
      ...DEFAULT_CONFIG,
      targets: {
        copilot: { enabled: true, output: ".github/copilot-instructions.md" },
      },
    };

    const results = await compileAll(tempDir, config);
    expect(results[0].error).toBeUndefined();

    const content = await readFile(join(tempDir, ".github", "copilot-instructions.md"), "utf-8");
    expect(content).toContain("Generated by openspec");
  });

  it("includes shared header and footer", async () => {
    await writeFile(
      join(tempDir, ".openspec", "modules", "rules.md"),
      "Some rules."
    );

    const config: OpenSpecConfig = {
      ...DEFAULT_CONFIG,
      shared: {
        header: "# My Project Rules",
        footer: "End of rules.",
      },
      targets: {
        claude: { enabled: true, output: "CLAUDE.md" },
      },
    };

    const results = await compileAll(tempDir, config);
    expect(results[0].error).toBeUndefined();

    const content = await readFile(join(tempDir, "CLAUDE.md"), "utf-8");
    expect(content).toContain("# My Project Rules");
    expect(content).toContain("End of rules.");
  });
});
