import { readFile } from "node:fs/promises";
import { join } from "node:path";
import chalk from "chalk";
import { loadConfig } from "../config.js";
import { compileAll } from "../compiler.js";
import { discoverModules } from "../modules.js";
import { TARGET_DESCRIPTIONS } from "../types.js";

export async function runDiff(projectRoot: string): Promise<void> {
  const config = await loadConfig(projectRoot);
  const modules = await discoverModules(projectRoot, config.modulesDir);

  if (modules.length === 0) {
    console.log(chalk.yellow("No modules found. Run 'openspec init' to get started."));
    return;
  }

  console.log(chalk.blue("openspec diff — preview changes\n"));

  // Build what sync WOULD produce (into a temp dir), then compare
  const { mkdtemp } = await import("node:fs/promises");
  const { tmpdir } = await import("node:os");
  const { rm } = await import("node:fs/promises");

  const tempDir = await mkdtemp(join(tmpdir(), "openspec-diff-"));

  // Copy config to temp so compiler can use it
  const tempConfig = {
    ...config,
    targets: Object.fromEntries(
      Object.entries(config.targets).map(([name, tc]) => [
        name,
        { ...tc, output: join(tempDir, tc.output).replace(/\\/g, "/") },
      ])
    ),
  };

  // Compile to temp
  // We need to trick compileAll to write to temp - easier to just recompile manually
  const { filterModulesForTarget } = await import("../modules.js");
  const { renderForTarget } = await import("../targets/index.js");

  const BANNER = "<!-- Generated by openspec — DO NOT EDIT DIRECTLY -->\n<!-- Source: .openspec/modules/ | Regenerate: npx openspec sync -->\n\n";

  let hasChanges = false;

  for (const [targetName, targetConfig] of Object.entries(config.targets)) {
    if (!targetConfig.enabled) continue;

    const filtered = filterModulesForTarget(modules, targetName, targetConfig.modules);
    if (filtered.length === 0) continue;

    const rendered = renderForTarget(targetName, filtered, {
      header: targetConfig.header ?? config.shared?.header,
      footer: config.shared?.footer,
    });
    const newContent = BANNER + rendered;

    const outputPath = join(projectRoot, targetConfig.output);
    const label = TARGET_DESCRIPTIONS[targetName] ?? targetName;

    let existingContent: string | null = null;
    try {
      existingContent = await readFile(outputPath, "utf-8");
    } catch {
      // File doesn't exist
    }

    if (existingContent === null) {
      console.log(chalk.green(`+ ${label}`), chalk.dim(`(new file: ${targetConfig.output})`));
      hasChanges = true;
    } else if (existingContent === newContent) {
      console.log(chalk.dim(`  ${label} — no changes`));
    } else {
      console.log(chalk.yellow(`~ ${label}`), chalk.dim(`(${targetConfig.output})`));

      // Simple line-by-line diff
      const oldLines = existingContent.split("\n");
      const newLines = newContent.split("\n");
      showSimpleDiff(oldLines, newLines);
      hasChanges = true;
    }
  }

  await rm(tempDir, { recursive: true, force: true });

  console.log();
  if (hasChanges) {
    console.log(chalk.yellow("Run 'openspec sync' to apply these changes."));
  } else {
    console.log(chalk.green("Everything is in sync."));
  }
}

function showSimpleDiff(oldLines: string[], newLines: string[]): void {
  const maxLines = Math.max(oldLines.length, newLines.length);
  let diffCount = 0;
  const MAX_DIFF_LINES = 20;

  for (let i = 0; i < maxLines; i++) {
    const oldLine = oldLines[i];
    const newLine = newLines[i];

    if (oldLine === newLine) continue;

    if (diffCount >= MAX_DIFF_LINES) {
      console.log(chalk.dim(`    ... and more changes`));
      break;
    }

    if (oldLine !== undefined && newLine !== undefined) {
      console.log(chalk.red(`  - ${oldLine}`));
      console.log(chalk.green(`  + ${newLine}`));
    } else if (oldLine !== undefined) {
      console.log(chalk.red(`  - ${oldLine}`));
    } else if (newLine !== undefined) {
      console.log(chalk.green(`  + ${newLine}`));
    }
    diffCount++;
  }
}
