import { writeFile, mkdir, access } from "node:fs/promises";
import { join } from "node:path";
import chalk from "chalk";

const DEFAULT_CONFIG_YAML = `# openspec configuration
# Docs: https://github.com/user/openspec
version: 1

# Directory containing your rule modules
modulesDir: ".openspec/modules"

# Optional shared header/footer for all targets
# shared:
#   header: "# Project Rules"
#   footer: "---\\nGenerated by openspec"

# Target AI tools to sync to
# Set 'enabled: false' to disable a target
# Use 'modules' to specify which modules to include (default: all)
targets:
  claude:
    enabled: true
    output: CLAUDE.md

  cursor:
    enabled: true
    output: .cursorrules

  gemini:
    enabled: true
    output: GEMINI.md

  copilot:
    enabled: true
    output: .github/copilot-instructions.md

  aider:
    enabled: true
    output: .aiderrules

  codex:
    enabled: true
    output: AGENTS.md

  windsurf:
    enabled: true
    output: .windsurfrules
`;

const EXAMPLE_SHARED_MODULE = `---
name: Project Overview
description: Core project rules that apply to all AI tools
priority: 10
---

# Project Overview

- This project uses [describe your stack here]
- Always follow existing code patterns and conventions
- Write clean, readable code with meaningful variable names
- Prefer composition over inheritance
`;

const EXAMPLE_FRONTEND_MODULE = `---
name: Frontend Conventions
description: Frontend-specific rules and patterns
priority: 20
tags: [frontend, react]
# Uncomment to only include in specific targets:
# targets: [claude, cursor]
# Uncomment to exclude from specific targets:
# excludeTargets: [aider]
---

# Frontend Conventions

- Use functional components with hooks
- Prefer named exports over default exports
- Co-locate tests with components (Component.test.tsx)
- Use CSS modules or Tailwind for styling — no inline styles
`;

const EXAMPLE_BACKEND_MODULE = `---
name: Backend Conventions
description: Backend-specific rules and patterns
priority: 20
tags: [backend, api]
---

# Backend Conventions

- Use dependency injection for services
- All API endpoints must have input validation
- Use structured logging (not console.log)
- Database queries must use parameterized statements
`;

const EXAMPLE_TESTING_MODULE = `---
name: Testing Standards
description: Testing conventions and requirements
priority: 30
tags: [testing]
---

# Testing Standards

- Write unit tests for all business logic
- Use descriptive test names: "should [expected behavior] when [condition]"
- Prefer integration tests for API endpoints
- Mock external services, never real databases in unit tests
`;

export async function runInit(projectRoot: string): Promise<void> {
  const openspecDir = join(projectRoot, ".openspec");
  const modulesDir = join(openspecDir, "modules");

  // Check if already initialized
  try {
    await access(openspecDir);
    console.log(chalk.yellow("⚠ .openspec/ directory already exists."));
    console.log(chalk.dim("  Delete it first if you want to reinitialize."));
    return;
  } catch {
    // Good, doesn't exist yet
  }

  // Create directories
  await mkdir(modulesDir, { recursive: true });

  // Write config
  await writeFile(join(openspecDir, "config.yaml"), DEFAULT_CONFIG_YAML);

  // Write example modules
  await writeFile(join(modulesDir, "shared.md"), EXAMPLE_SHARED_MODULE);
  await writeFile(join(modulesDir, "frontend.md"), EXAMPLE_FRONTEND_MODULE);
  await writeFile(join(modulesDir, "backend.md"), EXAMPLE_BACKEND_MODULE);
  await writeFile(join(modulesDir, "testing.md"), EXAMPLE_TESTING_MODULE);

  console.log(chalk.green("✓ Initialized openspec!\n"));
  console.log("  Created:");
  console.log(chalk.dim("  .openspec/config.yaml        — Configuration"));
  console.log(chalk.dim("  .openspec/modules/shared.md   — Shared rules"));
  console.log(chalk.dim("  .openspec/modules/frontend.md — Frontend rules"));
  console.log(chalk.dim("  .openspec/modules/backend.md  — Backend rules"));
  console.log(chalk.dim("  .openspec/modules/testing.md  — Testing rules"));
  console.log();
  console.log("  Next steps:");
  console.log(chalk.cyan("  1. Edit the modules in .openspec/modules/"));
  console.log(chalk.cyan("  2. Run 'openspec sync' to generate all AI context files"));
  console.log(chalk.cyan("  3. Run 'openspec watch' for auto-sync during development"));
}
