import { readFile, access } from "node:fs/promises";
import { join } from "node:path";
import chalk from "chalk";
import { loadConfig } from "../config.js";
import { discoverModules } from "../modules.js";
import { TARGET_DESCRIPTIONS } from "../types.js";

export async function runStatus(projectRoot: string): Promise<void> {
  const config = await loadConfig(projectRoot);
  const modules = await discoverModules(projectRoot, config.modulesDir);

  console.log(chalk.blue("openspec status\n"));

  // Modules
  console.log(chalk.bold("Modules:"), chalk.dim(`(${config.modulesDir})`));
  if (modules.length === 0) {
    console.log(chalk.yellow("  No modules found. Run 'openspec init' to get started."));
  } else {
    for (const mod of modules) {
      const name = mod.frontmatter.name ?? mod.slug;
      const tags = mod.frontmatter.tags?.length
        ? chalk.dim(` [${mod.frontmatter.tags.join(", ")}]`)
        : "";
      const prio = chalk.dim(` (priority: ${mod.frontmatter.priority})`);
      console.log(`  ${chalk.cyan(name)}${tags}${prio}`);
    }
  }

  console.log();

  // Targets
  console.log(chalk.bold("Targets:"));
  for (const [name, targetConfig] of Object.entries(config.targets)) {
    const label = TARGET_DESCRIPTIONS[name] ?? name;
    const outputPath = join(projectRoot, targetConfig.output);

    let status: string;
    if (!targetConfig.enabled) {
      status = chalk.dim("disabled");
    } else {
      try {
        await access(outputPath);
        const content = await readFile(outputPath, "utf-8");
        const isManaged = content.includes("Generated by openspec");
        status = isManaged
          ? chalk.green("synced")
          : chalk.yellow("exists (not managed by openspec)");
      } catch {
        status = chalk.red("missing — run 'openspec sync'");
      }
    }

    console.log(`  ${label}: ${status}`);
  }
}
