#!/usr/bin/env node

import { Command } from "commander";
import chalk from "chalk";
import { resolve } from "node:path";
import { runInit } from "./commands/init.js";
import { runSync } from "./commands/sync.js";
import { runStatus } from "./commands/status.js";
import { runDiff } from "./commands/diff.js";
import { runAdd } from "./commands/add.js";
import { runAnalyze } from "./commands/analyze.js";
import { loadConfig } from "./config.js";
import { startWatcher } from "./watcher.js";
import { installHook, removeHook } from "./hooks.js";
import { runInstall } from "./commands/install.js";

const program = new Command();

program
  .name("openspec")
  .description("The universal AI context infrastructure. Let AI generate your project rules, we sync them everywhere.")
  .version("0.2.2");

program
  .command("init")
  .description("Initialize openspec in the current project")
  .action(async () => {
    const root = resolve(".");
    await runInit(root);
  });

program
  .command("sync")
  .description("Compile modules and sync all AI context files")
  .option("-q, --quiet", "Suppress output (for use in hooks/scripts)")
  .action(async (options) => {
    const root = resolve(".");
    await runSync(root, options);
  });

program
  .command("watch")
  .description("Watch modules for changes and auto-sync")
  .action(async () => {
    const root = resolve(".");
    const config = await loadConfig(root);

    // Do initial sync
    await runSync(root, {});
    console.log();

    // Start watching
    startWatcher(root, config);
  });

program
  .command("status")
  .description("Show current sync status of all targets")
  .action(async () => {
    const root = resolve(".");
    await runStatus(root);
  });

program
  .command("hooks")
  .description("Install or remove git pre-commit hook")
  .option("--remove", "Remove the openspec git hook")
  .action(async (options) => {
    const root = resolve(".");
    if (options.remove) {
      const removed = await removeHook(root);
      if (removed) {
        console.log(chalk.green("✓ Removed openspec git hook."));
      } else {
        console.log(chalk.yellow("No openspec hook found."));
      }
    } else {
      const installed = await installHook(root);
      if (installed) {
        console.log(chalk.green("✓ Installed openspec pre-commit hook."));
        console.log(chalk.dim("  AI context files will auto-sync on every commit."));
      } else {
        console.log(chalk.yellow("⚠ Not a git repository. Initialize git first."));
      }
    }
  });

program
  .command("diff")
  .description("Preview what changes sync would make")
  .action(async () => {
    const root = resolve(".");
    await runDiff(root);
  });

program
  .command("add <name>")
  .description("Create a new rule module")
  .option("-p, --priority <number>", "Priority (lower = earlier)", "50")
  .option("-t, --targets <list>", "Comma-separated target whitelist")
  .option("--tags <list>", "Comma-separated tags")
  .action(async (name: string, options) => {
    const root = resolve(".");
    await runAdd(root, name, options);
  });

program
  .command("analyze")
  .description("Analyze codebase and output context for AI-powered rule generation")
  .option("--json", "Output as JSON instead of markdown")
  .option("-o, --output <path>", "Write analysis to file instead of stdout")
  .option("-q, --quiet", "Suppress non-essential output")
  .action(async (options) => {
    const root = resolve(".");
    await runAnalyze(root, options);
  });

program
  .command("install")
  .description("Install OpenSpec Claude Code Plugin")
  .action(async () => {
    const root = resolve(".");
    await runInstall(root);
  });

program
  .command("clean")
  .description("Remove all generated AI context files")
  .action(async () => {
    const { unlink } = await import("node:fs/promises");
    const root = resolve(".");
    const config = await loadConfig(root);

    let removed = 0;
    for (const [name, targetConfig] of Object.entries(config.targets)) {
      const outputPath = resolve(root, targetConfig.output);
      try {
        const { readFile } = await import("node:fs/promises");
        const content = await readFile(outputPath, "utf-8");
        if (content.includes("Generated by openspec")) {
          await unlink(outputPath);
          console.log(chalk.dim(`  Removed ${targetConfig.output}`));
          removed++;
        } else {
          console.log(chalk.yellow(`  Skipped ${targetConfig.output} (not managed by openspec)`));
        }
      } catch {
        // File doesn't exist, skip
      }
    }

    if (removed > 0) {
      console.log(chalk.green(`\n✓ Cleaned ${removed} generated file(s).`));
    } else {
      console.log(chalk.dim("No generated files to clean."));
    }
  });

program.parse();
