import { writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import type { OpenSpecConfig, ParsedModule, SyncResult, TargetConfig } from "./types.js";
import { discoverModules, filterModulesForTarget } from "./modules.js";
import { renderForTarget } from "./targets/index.js";

const GENERATED_BANNER = "<!-- Generated by openspec — DO NOT EDIT DIRECTLY -->\n<!-- Source: .openspec/modules/ | Regenerate: npx openspec sync -->\n\n";

export async function compileAll(projectRoot: string, config: OpenSpecConfig): Promise<SyncResult[]> {
  const modules = await discoverModules(projectRoot, config.modulesDir);
  const results: SyncResult[] = [];

  if (modules.length === 0) {
    return [];
  }

  for (const [targetName, targetConfig] of Object.entries(config.targets)) {
    if (!targetConfig.enabled) {
      results.push({
        target: targetName,
        outputPath: targetConfig.output,
        modulesIncluded: [],
        bytesWritten: 0,
        skipped: true,
      });
      continue;
    }

    try {
      const result = await compileTarget(
        projectRoot,
        targetName,
        targetConfig,
        modules,
        config
      );
      results.push(result);
    } catch (err) {
      results.push({
        target: targetName,
        outputPath: targetConfig.output,
        modulesIncluded: [],
        bytesWritten: 0,
        skipped: false,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }

  return results;
}

async function compileTarget(
  projectRoot: string,
  targetName: string,
  targetConfig: TargetConfig,
  allModules: ParsedModule[],
  config: OpenSpecConfig
): Promise<SyncResult> {
  const filtered = filterModulesForTarget(allModules, targetName, targetConfig.modules);

  if (filtered.length === 0) {
    return {
      target: targetName,
      outputPath: targetConfig.output,
      modulesIncluded: [],
      bytesWritten: 0,
      skipped: true,
    };
  }

  const rendered = renderForTarget(targetName, filtered, {
    header: targetConfig.header ?? config.shared?.header,
    footer: config.shared?.footer,
  });

  const output = GENERATED_BANNER + rendered;
  const outputPath = join(projectRoot, targetConfig.output);

  // Ensure output directory exists
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf-8");

  return {
    target: targetName,
    outputPath: targetConfig.output,
    modulesIncluded: filtered.map((m) => m.slug),
    bytesWritten: Buffer.byteLength(output, "utf-8"),
    skipped: false,
  };
}
